### ISSUE TITLE
Pysox tries to import numpy during build-time, only declared as a run-time dependency

### ISSUE THREAD

**Issue by Jacob-Bishop** [marl/pysox#167]
I was trying to install another module that depends on pysox, and ran into the error below, which seems to indicate that in the process of building pysox the module tries to read valid formats from core.py, which incidentally imports numpy (which isn't guaranteed to be installed yet, since the module declares numpy as an installation requirement and not a setup requirement). 

I can work around this by installing numpy first, but I ideally wouldn't have to manage sub-dependencies myself. I think the solution here would be to just store valid formats somewhere else, so you can read them during setup without having to run all the imports in core? 

FWIW, I found the following thread useful for understanding what's going on here: https://github.com/pypa/pip/issues/6193.

```
Collecting sox (from nemo-toolkit[all]==1.23.0)
  Downloading sox-1.5.0.tar.gz (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.9/63.9 kB 855.1 kB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [61 lines of output]
      /usr/lib/python3/dist-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 419, in _parse_attr
          return getattr(StaticModule(module_name), attr_name)
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 26, in __init__
          spec = importlib.util.find_spec(name)
        File "/usr/lib/python3.10/importlib/util.py", line 94, in find_spec
          parent = __import__(parent_name, fromlist=['__path__'])
        File "/tmp/pip-install-itwjnv3t/sox_3bc498e86177470ab7746acf9fa14cac/sox/__init__.py", line 21, in <module>
          from . import file_info
        File "/tmp/pip-install-itwjnv3t/sox_3bc498e86177470ab7746acf9fa14cac/sox/file_info.py", line 9, in <module>
          from .core import VALID_FORMATS
        File "/tmp/pip-install-itwjnv3t/sox_3bc498e86177470ab7746acf9fa14cac/sox/core.py", line 8, in <module>
          import numpy as np
      ModuleNotFoundError: No module named 'numpy'
```

**Comment by gnodabb** [comment]
If you get around it by installing numpy first. Then you get a similar error with 'typing_extensions'.

So the workaround is to run:
`pip install numpy typing_extensions`

Then:
`pip install sox`

**Comment by katoudaj** [comment]
I also encountered this issue while trying to install another module that depends on pysox.
When I cloned this project and ran `pip install .`, I got the same error as below.
(Sorry for the Japanese text in the log.)

<details> <summary>Error log</summary>

```
pip install .
Processing c:\users\username\desk\temp__\pysox
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [99 lines of output]
      'sox' は、内部コマンドまたは外部コマンド、
      操作可能なプログラムまたはバッチ ファイルとして認識されていません。
      SoX could not be found!
      
          If you do not have SoX, proceed here:
           - - - http://sox.sourceforge.net/ - - -
      
          If you do (or think that you should) have SoX, double-check your
          path variables.
      
      'sox' は、内部コマンドまたは外部コマンド、
      操作可能なプログラムまたはバッチ ファイルとして認識されていません。  
      SoX could not be found!

          If you do not have SoX, proceed here:
           - - - http://sox.sourceforge.net/ - - -

          If you do (or think that you should) have SoX, double-check your 
          path variables.

      'sox' は、内部コマンドまたは外部コマンド、
      操作可能なプログラムまたはバッチ ファイルとして認識されていません。  
      SoX could not be found!

          If you do not have SoX, proceed here:
           - - - http://sox.sourceforge.net/ - - -

          If you do (or think that you should) have SoX, double-check your 
          path variables.
      
      'sox' は、内部コマンドまたは外部コマンド、
      操作可能なプログラムまたはバッチ ファイルとして認識されていません。  
      SoX could not be found!

          If you do not have SoX, proceed here:
           - - - http://sox.sourceforge.net/ - - -

          If you do (or think that you should) have SoX, double-check your 
          path variables.

      Traceback (most recent call last):
        File "C:\Users\username\desk\temp__\pysox\env\lib\site-packages\setuptools\config.py", line 419, in _parse_attr
          return getattr(StaticModule(module_name), attr_name)
        File "C:\Users\username\desk\temp__\pysox\env\lib\site-packages\setuptools\config.py", line 26, in __init__
          spec = importlib.util.find_spec(name)
        File "C:\Users\username\.pyenv\pyenv-win\versions\3.10.5\lib\importlib\util.py", line 94, in find_spec
          parent = __import__(parent_name, fromlist=['__path__'])
        File "C:\Users\username\desk\temp__\pysox\sox\__init__.py", line 21, in <module>
          from . import file_info
        File "C:\Users\username\desk\temp__\pysox\sox\file_info.py", line 9, in <module>
          from .core import VALID_FORMATS
        File "C:\Users\username\desk\temp__\pysox\sox\core.py", line 8, in <module>
          import numpy as np
      ModuleNotFoundError: No module named 'numpy'

      During handling of the above exception, another exception occurred:  

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\username\desk\temp__\pysox\setup.py", line 10, in <module>
          setup(
        File "C:\Users\username\desk\temp__\pysox\env\lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\username\.pyenv\pyenv-win\versions\3.10.5\lib\distutils\core.py", line 121, in setup
          dist.parse_config_files()
        File "C:\Users\username\desk\temp__\pysox\env\lib\site-packages\setuptools\dist.py", line 798, in parse_config_files
          parse_configuration(
        File "C:\Users\username\desk\temp__\pysox\env\lib\site-packages\setuptools\config.py", line 158, in parse_configuration
          meta.parse()
        File "C:\Users\username\desk\temp__\pysox\env\lib\site-packages\setuptools\config.py", line 498, in parse
          section_parser_method(section_options)
        File "C:\Users\username\desk\temp__\pysox\env\lib\site-packages\setuptools\config.py", line 469, in parse_section
          self[name] = value
        File "C:\Users\username\desk\temp__\pysox\env\lib\site-packages\setuptools\config.py", line 222, in __setitem__
          value = parser(value)
        File "C:\Users\username\desk\temp__\pysox\env\lib\site-packages\setuptools\config.py", line 597, in _parse_version
          version = self._parse_attr(value, self.package_dir)
        File "C:\Users\username\desk\temp__\pysox\env\lib\site-packages\setuptools\config.py", line 422, in _parse_attr
          module = importlib.import_module(module_name)
        File "C:\Users\username\.pyenv\pyenv-win\versions\3.10.5\lib\importlib\__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)      
        File "<frozen importlib._bootstrap>", line 1050, in _gcd_import    
        File "<frozen importlib._bootstrap>", line 1027, in _find_and_load 
        File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1050, in _gcd_import    
        File "<frozen importlib._bootstrap>", line 1027, in _find_and_load 
        File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 688, in _load_unlocked  
        File "<frozen importlib._bootstrap_external>", line 883, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "C:\Users\username\desk\temp__\pysox\sox\__init__.py", line 21, in <module>
          from . import file_info
        File "C:\Users\username\desk\temp__\pysox\sox\file_info.py", line 9, in <module>
          from .core import VALID_FORMATS
        File "C:\Users\username\desk\temp__\pysox\sox\core.py", line 8, in <module>
          import numpy as np
      ModuleNotFoundError: No module named 'numpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

</details>

Here’s what’s happening behind the scenes:
- When running `pip install .`, pip first executes setup.py to generate package metadata.
- Because `packages=['sox']` is specified, setuptools inspects the `sox` directory.
- During this process, `sox/__init__.py` is loaded.
In the case of pysox:
`sox/__init__.py` imports `file_info`,
`file_info.py` imports `core`,
and `core.py` contains
```
import numpy as np
from typing_extensions import Literal
```
This means that even though `setup.py` itself does not import NumPy, setuptools tries to import it while inspecting the package, before NumPy and typing_extensions are installed, causing the error.

I was able to fix this by adding a `pyproject.toml` file at the project root:
```
[build-system]
requires = ["setuptools>=42", "wheel", "numpy", "typing-extensions"]
build-backend = "setuptools.build_meta"
```
Using `pyproject.toml` ensures that build-time dependencies (like NumPy) are installed before running `setup.py`, which resolves the issue.
